import { Patient } from "@/app/types/triage";

export const waitingPatients: Patient[] = [
  {
    id: "1",
    cedula: "1.045.678.901",
    name: "María",
    lastName: "González Ruiz",
    fullName: "María González Ruiz",
    age: 42,
    dateOfBirth: "1983-05-12",
    gender: "Femenino",
    address: "Calle 12 #34-56, Bogotá",
    phone: "3001234567",
    email: "maria.gonzalez@example.com",
    chiefComplaint: "💔 Dolor Torácico",
    arrivalTime: "14:23",
    chatCompleted: false,
  },
  {
    id: "2",
    cedula: "1.098.234.567",
    name: "Juan",
    lastName: "Pérez Morales",
    fullName: "Juan Pérez Morales",
    age: 36,
    dateOfBirth: "1987-02-18",
    gender: "Masculino",
    address: "Carrera 45 #67-89, Bogotá",
    phone: "3009876543",
    email: "juan.perez@example.com",
    chiefComplaint: "🦶 Trauma en Tobillo",
    arrivalTime: "14:35",
    chatCompleted: false,
  },
  {
    id: "3",
    cedula: "52.876.543",
    name: "Ana",
    lastName: "Martínez López",
    fullName: "Ana Martínez López",
    age: 29,
    dateOfBirth: "1994-08-03",
    gender: "Femenino",
    address: "Av. Caracas #12-34, Bogotá",
    phone: "3112233445",
    email: "ana.martinez@example.com",
    chiefComplaint: "😰 Dificultad Respiratoria",
    arrivalTime: "14:48",
    chatCompleted: false,
  },
  {
    id: "4",
    cedula: "1.234.567.890",
    name: "Carlos",
    lastName: "Ramírez Torres",
    fullName: "Carlos Ramírez Torres",
    age: 50,
    dateOfBirth: "1973-11-25",
    gender: "Masculino",
    address: "Calle 78 #56-23, Bogotá",
    phone: "3005678901",
    email: "carlos.ramirez@example.com",
    chiefComplaint: "🤒 Fiebre alta",
    arrivalTime: "15:00",
    chatCompleted: false,
  },
  {
    id: "5",
    cedula: "987.654.321",
    name: "Laura",
    lastName: "Sánchez Díaz",
    fullName: "Laura Sánchez Díaz",
    age: 33,
    dateOfBirth: "1991-04-15",
    gender: "Femenino",
    address: "Carrera 56 #78-90, Bogotá",
    phone: "3123344556",
    email: "laura.sanchez@example.com",
    chiefComplaint: "🤕 Cefalea intensa",
    arrivalTime: "15:12",
    chatCompleted: false,
  },
];
